# Computer Vision

Computer Vision bilgisayarların görüntüleri anlamasına ve yorumlamasına yardımcı olur. Görüntülerin veya videoların analizi ve işlenmesi yoluyla, bilgisayarlar görüntülerdeki nesneleri, yüzleri, cisimleri ve diğer özellikleri algılayabilir ve tanıyabilir.

Computer Vision görsel işleme, makine öğrenimi ve yapay zeka tekniklerini kullanır. Görüntüler üzerindeki işlemler, piksel düzeyinde başlar ve daha yüksek seviyeli anlamlar ve bilgiler çıkarmak için ilerler. Örneğin, bir görüntüdeki kenarları algılamak, nesneleri tespit etmek veya yüzleri tanımak gibi görevler gerçekleştirilebilir.

### OpenCv Kütüphanesi Kullanımı
OpenCv kütüphanesi kullanarak aşağıdaki işlemler yapılabilir:

1- 
2- 
3- 
.
.

### 0- Kütüphanenin kurulumu

In [6]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: opencv-python in c:\users\salih\appdata\local\programs\python\python311\lib\site-packages (4.9.0.80)




[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import cv2
#cv2 kütüphanesini import ettik

import numpy as np
#numpy kütüphanesini np kısaltması kullanacak şekilde import ettik

### 1- Değişken Oluşturma

In [44]:
resim = cv2.imread("aslan.jpg")
#bir resim değişkeni oluşturduk ve resmimizi cv2 ye tanıttık okumasını sağladık


### 2- Resmi Çıktı Gösterme ve Resim Bilgisi

In [45]:
cv2.imshow("aslan",resim)
#imshow kullanarak resmi çıktı olarak gösterdik,resim bilgisinde de aslan yazmasını sağladık
cv2.waitKey(0)
#waitkey metodu ile açtığımız resim biz bir tuşa basana kadar açık kalacaktır
cv2.destroyAllWindows()
#bu metod sayesinde açılan pencereyi kapattığımızda arka planda çalışan tüm opencv kodları kapanacaktır

### 3- Resim Piksel Matrisleri

In [46]:
print(resim)
#resim dosyamızı yazdırdığımızda resmimizin piksellerini matrislerini bize listeler (BGR)

[[[153 150 165]
  [153 150 165]
  [153 150 165]
  ...
  [118  99  92]
  [118  99  92]
  [118  99  92]]

 [[154 151 166]
  [154 151 166]
  [154 151 166]
  ...
  [118  99  92]
  [118  99  92]
  [118  99  92]]

 [[154 151 166]
  [154 151 166]
  [154 151 166]
  ...
  [118  99  92]
  [118  99  92]
  [118  99  92]]

 ...

 [[ 20  35  44]
  [ 21  36  45]
  [ 22  37  46]
  ...
  [ 13  37  65]
  [ 13  37  65]
  [ 13  37  65]]

 [[ 19  34  43]
  [ 21  36  45]
  [ 23  38  47]
  ...
  [ 28  57  88]
  [ 26  57  88]
  [ 23  57  87]]

 [[ 19  34  43]
  [ 21  36  45]
  [ 23  38  47]
  ...
  [ 50  79 110]
  [ 47  78 109]
  [ 45  79 109]]]


### 4- Resim Hakkında Bilgi

In [47]:
print(resim.size)
#resmin boyutunu yazar
print(resim.dtype)
#resmin taypı nedir onu gösterir
print(resim.shape)
#resim hakkında daha detaylı(yükseklik,genişlik,kanal)bilgisi verir.

1607472
uint8
(549, 976, 3)


### 5- Piksel Renk Değeri Görme

In [48]:
print(resim[230,80])
#belirtilen konumdaki pikselin renk değerlerini gördük (BGR)

[161 177 200]


### 6-  Piksel Boyama

In [49]:
for i in range(100):
    resim[50,i]=[255,255,255]

cv2.imshow("aslan",resim)   
cv2.waitKey(0)
cv2.destroyAllWindows() 

#belirtilen piksel konumundan itibaren döngü ile sınırladığımız konuma kadar olan pikselleri beyaza boyadık.

### 7- Resim Efektlendirme

In [50]:
resim[:,:,0]=255
resim[:,:,1]=100
cv2.imshow("aslan",resim)   
cv2.waitKey(0)
cv2.destroyAllWindows() 
#bgr renk sayılarını kullanarak resme efekt ekledik

### 8- Belli Bölgeyi Efektlendirme

In [51]:
resim2= cv2.imread("cengiz.jpeg")
resim2[90:120,200:400,0]=255
resim2[90:120,200:400,1]=200
resim2=cv2.imshow("cengizhan",resim2)
cv2.waitKey(0)
cv2.destroyAllWindows() 
#yeni bir resim tanımladık piksel konumlarını ve bgr renk kodlarını kullanarak remin belli bir noktasına efekt ekledik

### 9- Aynalama

In [52]:
import cv2
#cv2 kütüphanesini import ettik

import numpy as np

resim2= cv2.imread("cengiz.jpeg")
aynalama= cv2.copyMakeBorder(resim2,200,200,500,500,cv2.BORDER_REFLECT)

cv2.imshow("Şener",aynalama)

cv2.waitKey(0)
cv2.destroyAllWindows() 
#yeni bir resim tanımladık ardından aynalama adında bir değişken açıp cv2'nin fonksyonlarından olan copyMakeBorder'ı kullandık resmimizi ve üst,alt,sağ,sol çerçevelerden ne kadar 
#aynalama yapacağımızı belirttik ve çalıştırdık


### 10- Belli Bölgeyi İşaretleme


In [53]:

import cv2
import numpy as np

resim3= cv2.imread("scooby.jpeg")
cv2.rectangle(resim3,(150,600),(450,200),[0,0,255],5)
cv2.imshow("ekip",resim3)

cv2.waitKey(0)
cv2.destroyAllWindows() 
#Resim3 adında bir değişken tanımladık ve resmimizi tanıttık,cv2'nin rectangle fonksyonunu kullanarak bir şekil çizdik girdiğimiz ilk değer sol alt köşenin x ve y değerleri ikinci değer ise sağ üst
# üçüncü değer köşeli parantez içerisinde olan renk ve son değer kalınlık 

### 11- Grileştirme

In [54]:
import cv2
import numpy as np

resim=cv2.imread("aslan.jpg")
resimGri=cv2.cvtColor(resim,cv2.COLOR_BGR2GRAY)
cv2.imshow("gri",resimGri)
cv2.imshow("orjinal",resim)

cv2.waitKey(0)
cv2.destroyAllWindows() 
#gerekli import işlemlerinden sonra cv2'nin cvtColor fonksyonunu kullanarak resmi grileştiriyoruz

### 12- Resmi İki Kat Büyütme-Küçültme

In [55]:
import cv2
import numpy as np

resim=cv2.imread("aslan.jpg")
ikikatbuyuk=cv2.pyrUp(resim)
ikikatkucuk=cv2.pyrDown(resim)
cv2.imshow("kucuk",ikikatkucuk)
cv2.imshow("buyuk",ikikatbuyuk)

cv2.waitKey(0)
cv2.destroyAllWindows() 
#cv2'nin pyrUp ve pyrDown fonksyonlarını kullanarak resmimizi ik kat küçültüp büyütebiliriz


### 13- Kamera İle Görüntü Alma

In [24]:
import cv2
import numpy as np

kamera=cv2.VideoCapture(0)
#kameramızı tanıttık 0 değeri pc kamerası kullanacağımız anlamına geliyor

while True:
    ret,goruntu=kamera.read()
    #kameranın çalışıp çalışmadığını kontrol etti ve goruntunun içine attı
    cv2.imshow("salihcankeskin",goruntu)

    if (cv2.waitKey(20) == ord('q')):
        break
    #20 ms lik fotoğraflar çekerek video yaptı ve q tuşuna basınca döngüden çıkmamızı yani kameranın kapnmasını sağladı
kamera.release()
#kamerayı serbest bıraktı

cv2.destroyAllWindows() 




### 14- Videoya Metin Kutusu - Çizgi ve Kutu Ekleme

In [56]:
import cv2
import numpy as np

kamera=cv2.VideoCapture(0)
#kameramızı tanıttık 0 değeri pc kamerası kullanacağımız anlamına geliyor

while True:
    ret,goruntu=kamera.read()
    #kameranın çalışıp çalışmadığını kontrol etti ve goruntunun içine attı
    cv2.rectangle(goruntu,(100,100),(200,200),(0,0,255),5)
    #kutu ekleme (değerlerin ne olduğu yukarıdaki kodlarda mevcut)
    cv2.line(goruntu,(0,0),(150,150),(0,0,100),2)
    #çizgi ekleme
    cv2.putText(goruntu,"Salihcan",(250,250),cv2.FONT_HERSHEY_COMPLEX,1,(200,0,0),5)
    #metin ekleme (cv2.FONT_HERSHEY_COMPLEX font belirler)

    cv2.imshow("salihcankeskin",goruntu)

    if (cv2.waitKey(20) == ord('q')):
        break
    #20 ms lik fotoğraflar çekerek video yaptı ve q tuşuna basınca döngüden çıkmamızı yani kameranın kapnmasını sağladı
kamera.release()
#kamerayı serbest bıraktı

cv2.destroyAllWindows() 

### 15- Mean - Median ve Gauss Filtreleme

In [57]:
import cv2
import numpy as np

gurultu=cv2.imread("gurultuluresim.png")
kgurultu=cv2.pyrDown(gurultu)

meanFilter=cv2.blur(kgurultu,(5,5))
#5x5 lik bir ızgara üzerinden pikselleri ayırır ve orta değerdeki piksele yakın olacak şekilde resmi yumuşatır

medianFilter=cv2.medianBlur(kgurultu,5)
#kaçlık bir ızgara istiyorsak parametre olarak gireriz ızgaralardaki piksellerin aritmetik ortalamasını alır ve çıkan piksele göre yumuşatma yapar

gauss=cv2.GaussianBlur(kgurultu,(3,3),0)
#aynı işlevi yani yumuşatma yapar ancak ızgarası çan eğrisi şekilndedirr.

cv2.imshow("orjinal",kgurultu)
cv2.imshow("meanfilter",meanFilter)
cv2.imshow("medianfilter",medianFilter)
cv2.imshow("gauss",gauss)

cv2.waitKey(0)
cv2.destroyAllWindows()

### 16- Otomatik Kenarlık Yapma (Auto canny)

In [58]:
import cv2
import numpy as np

image=cv2.imread("ornek1.jpg")
#resmimizi tanımladık



def autoCanny(image,sigma=0.75):
#otomatik bir fonksyon yapmak için def kullandık ve şartlarımızı belirledik
    median=np.median(image)
    #fotoğrafın medyanını bulduk yukarıda yapmıştık 
    lower=int (max(0,(1.0-sigma)*median))
    #alt değer olarak tamdan sigmayı çıkardık
    upper=int(min(255,(1.0+sigma)*median))
    #üst değer olarak da tama sigmayı ekledik
    canny=cv2.Canny(image,lower,upper)
    #kenarlık olarak bu alt ve üst değerleri referans aldık 

    return canny

wide=cv2.Canny(image,10,220)
#kenarlığın şartlarını manuel belirledik detaylı bir kenarlık yakın bir kenarlık yaptık 
tight=cv2.Canny(image,200,230)
#kenarlığın şartlarını manuel belirledik uzak bir kenarlık yaptık 
auto=autoCanny(image)
#yazdığımız otomatik kenarlık fonksyonunu auto adlı değişkene attık

cv2.imshow("orj",image)
#orjinal fotoğrafı gösterdik
cv2.imshow("kenarliklilar",np.hstack([wide,tight,auto]))
#yaptığımız kenarlıklı fotoğrafları yan yana dizip tek bir fotoğrafta gösterdik

cv2.waitKey(0)
cv2.destroyAllWindows()

### 17- Web Kamerasından Görüntü Kaydetme

In [1]:
import cv2

camera=cv2.VideoCapture(0)

width=int(camera.get(cv2.CAP_PROP_FRAME_WIDTH))
#açılan kamera ızgarasının genişliğini aldık 
height=int(camera.get(cv2.CAP_PROP_FRAME_HEIGHT))
#açılan kamera ızgarasının yüksekliğini aldık 

print(width,height)

fourcc=cv2.VideoWriter_fourcc(*'MP4V')
#kayıt edilecek olan görüntü formatını belirttik

writer=cv2.VideoWriter("kayit.mp4",fourcc,20,(width,height))
#kaydı yazdırdık 

while True:
    ret,frame=camera.read()
    writer.write(frame)
    cv2.imshow("Salihcan Kayit",frame)

    if (cv2.waitKey(25)== ord('q')):
        break

camera.release()
writer.release()
#q ya basınca kaydın da durmasını sağladık 
cv2.destroyAllWindows()

#çekilen kaydı kodun bulunduğu dosya içerisinde bulaabilirssiniz.


640 360


### 18- Resimdeki Yüzleri Bulma

In [2]:
import cv2

face_cascade=cv2.CascadeClassifier(r"haarcascade_frontalface_default.xml")
#Yüz tanıması içn yüzlerin bulunduğu xml dosyası
img= cv2.imread(r"yenisalih.png")
gray=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

faces=face_cascade.detectMultiScale(gray,1.1,4)

for(x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),3)
    #tespit edilen yüz etrafına dikdörtgen çiziyoruz

cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 19-Videodaki Yüzleri Tespit Etme

In [2]:

import cv2

face_cascade = cv2.CascadeClassifier(
    r"haarcascade_frontalface_default.xml")

cap = cv2.VideoCapture(r"videosalih.mp4")
while cap.isOpened():
    _,img = cap.read()

   
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    faces = face_cascade.detectMultiScale(gray,1.1,4)

    for(x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w, y+h),(0,255,0),3)

    cv2.imshow('img',img)
    if (cv2.waitKey(25)== ord('q')):
        break

cap.release()